### ISSUE TITLE
Suggestion: Use for loop for element macro

### ISSUE THREAD

**Issue by bullno1** [nicbarker/clay#28] opened 2024-09-24 14:03 UTC
Instead of making the children code the last argument, the open/close calls can be made into a for loop:

```c
for (int i = (Clay__Open(...), 0), i < 1; ++i, Clay__Close()) {
    // children code
}
```

`CLAY_RECTANGLE` for example, can be defined as:

```c
#define CLAY_RECTANGLE(...) for (int i = (Clay__OpenRectangleElement(__VA_ARGS__), 0); i < 1;  ++i, Clay__CloseElementWithChildren())
```

It can be seen in action here: https://github.com/bullno1/cute-clay/blob/master/src/plugin_main.c#L76-L87
Definition: https://github.com/bullno1/cute-clay/blob/master/src/cute_clay.h#L17-L18

One advantage over the current method is that the children code is not smashed into one line by macro expansion.
It can be easily stepped over by a debugger.
Syntax highlighting or code completion would also be better since it's not inside a macro.

The disadvantage is that empty containers must end with `{}` or the next line will get roped into the loop.

**Comment by nicbarker** [comment] 2024-09-24 22:04
Hello and thanks for opening the issue, this is super interesting! I will do some local experimentation with this today and get back to you 😁

**Comment by nicbarker** [comment] 2024-09-24 23:05
This is genius! I'm a huge fan of the way it just "works" with the debugger, and prevents the macros being turned into one giant expansion. Some issues that need to be thought about:

- "Declaration shadows a local variable" warning because of the loop index variable. Not sure if there is a way around this one, but will have a play around and see.
- It's a bit of a silent footgun if the user forgets the `{}` and the subsequent element gets parented inside the previous one.

**Comment by nicbarker** [comment] 2024-09-24 23:36
Re: the first point, the following works ok, as long as you don't nest multiple elements on one line:

<img width="489" alt="Screenshot 2024-09-25 at 11 35 53 AM" src="https://github.com/user-attachments/assets/0a150ec5-e155-4985-8d12-e6ae58a4eac2">

**Comment by nicbarker** [comment] 2024-09-24 23:55
Ah - I see you solved it using a variable postfixed with the `__LINE__` of the macro. Seems like it's possible to use just a global latch here, something like this:

<img width="576" alt="Screenshot 2024-09-25 at 11 55 02 AM" src="https://github.com/user-attachments/assets/74b3372d-210f-4234-945a-288d6fbb2cc2">

Which will avoid having to define a whole bunch of local loop vars during layout creation 👍

**Comment by nicbarker** [comment] 2024-09-28 03:51
This has been addressed in https://github.com/nicbarker/clay/pull/30 - will temporarily leave the issue open while it's confirmed that it solves the original issue adequately 🙂

**Comment by nicbarker** [comment] 2024-10-03 20:39
I think this has been adequately, so going to close this one!

**Closed by nicbarker** 2024-10-03 20:39 UTC
Labels: enhancement, Attempted Fix
