### ISSUE TITLE
"initializer element is not constant" error on certain compilers

### ISSUE THREAD

**Issue by haifenghuang** [nicbarker/clay#24] opened 2024-09-24 12:33 UTC
I use WSL ubuntu on windows, when I run the cmake generated Makefile like below :

```sh
$ cd example
$ make
````

It report below errors:
```
[ 98%] Building C object examples/raylib-sidebar-scrolling-container/CMakeFiles/clay_examples_raylib_sidebar_scrolling_container.dir/main.c.o
In file included from /home/huanghaifeng/clay-main/examples/raylib-sidebar-scrolling-container/main.c:2:
/home/huanghaifeng/clay-main/examples/raylib-sidebar-scrolling-container/../../clay.h:1307:69: error: initializer element is not constant
 1307 | Clay_ElementId Clay__dynamicElementIndexBaseHash = (Clay_ElementId) { .id = 128476991, .stringId = CLAY_STRING("Auto ID") };
      |                                                                     ^
/home/huanghaifeng/clay-main/examples/raylib-sidebar-scrolling-container/../../clay.h:1307:69: note: (near initialization for ‘Clay__dynamicElementIndexBaseHash’)
/home/huanghaifeng/clay-main/examples/raylib-sidebar-scrolling-container/../../clay.h:1307:52: error: initializer element is not constant
 1307 | Clay_ElementId Clay__dynamicElementIndexBaseHash = (Clay_ElementId) { .id = 128476991, .stringId = CLAY_STRING("Auto ID") };
      |                                                    ^
/home/huanghaifeng/clay-main/examples/raylib-sidebar-scrolling-container/../../clay.h:2444:82: error: initializer element is not constant
 2444 | Clay_TextElementConfig Clay__DebugView_TextNameConfig = (Clay_TextElementConfig) {.fontSize = 16, .textColor = CLAY__DEBUGVIEW_COLOR_4, .wrapMode = CLAY_TEXT_WRAP_NONE };
      |                                                                                  ^
/home/huanghaifeng/clay-main/examples/raylib-sidebar-scrolling-container/../../clay.h:2444:82: note: (near initialization for ‘Clay__DebugView_TextNameConfig’)
/home/huanghaifeng/clay-main/examples/raylib-sidebar-scrolling-container/../../clay.h:2444:57: error: initializer element is not constant
 2444 | Clay_TextElementConfig Clay__DebugView_TextNameConfig = (Clay_TextElementConfig) {.fontSize = 16, .textColor = CLAY__DEBUGVIEW_COLOR_4, .wrapMode = CLAY_TEXT_WRAP_NONE };
      |                                                         ^
/home/huanghaifeng/clay-main/examples/raylib-sidebar-scrolling-container/main.c:14:68: error: initializer element is not constant
   14 | Clay_TextElementConfig headerTextConfig = (Clay_TextElementConfig) { .fontId = FONT_ID_BODY_16, .fontSize = 16, .textColor = {0,0,0,255} };
      |                                                                    ^
/home/huanghaifeng/clay-main/examples/raylib-sidebar-scrolling-container/main.c:14:68: note: (near initialization for ‘headerTextConfig’)
/home/huanghaifeng/clay-main/examples/raylib-sidebar-scrolling-container/main.c:14:43: error: initializer element is not constant
   14 | Clay_TextElementConfig headerTextConfig = (Clay_TextElementConfig) { .fontId = FONT_ID_BODY_16, .fontSize = 16, .textColor = {0,0,0,255} };
      |                                           ^
make[2]: *** [examples/raylib-sidebar-scrolling-container/CMakeFiles/clay_examples_raylib_sidebar_scrolling_container.dir/build.make:76: examples/raylib-sidebar-scrolling-container/CMakeFiles/clay_examples_raylib_sidebar_scrolling_container.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:183: examples/raylib-sidebar-scrolling-container/CMakeFiles/clay_examples_raylib_sidebar_scrolling_container.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by nicbarker** [comment] 2024-09-24 21:50
Hello and thanks for the report, I'll take a look at this today.

**Comment by nicbarker** [comment] 2024-09-25 01:32
Could you clarify which compiler and version this is?

**Comment by nicbarker** [comment] 2024-09-25 01:40
Ah I see, I've reproduced this with `gcc`. I'm using clang on my local machine and it accepts these types of initializers. I'll double check if upping the `gcc` version fixes the problem, otherwise I'll replace those declarations with macros.

**Comment by nicbarker** [comment] 2024-09-25 01:44
Please try out this commit and see if it fixes your problem: https://github.com/nicbarker/clay/commit/3775927e4030cc42d8861b9a66062b15e0a217e6 🙂

**Comment by haifenghuang** [comment] 2024-09-25 02:39
> Please try out this commit and see if it fixes your problem: [3775927](https://github.com/nicbarker/clay/commit/3775927e4030cc42d8861b9a66062b15e0a217e6) 🙂

This commit fixed the `clay.h` error, but when I make the `clay-official-website` directory, it report below errors:

```
$ make
[ 50%] Building C object examples/clay-official-website/CMakeFiles/clay_official_website.dir/main.c.o
In file included from /home/huanghaifeng/clay-main/examples/clay-official-website/main.c:5:
/home/huanghaifeng/clay-main/examples/clay-official-website/../../clay.h:1307:69: error: initializer element is not constant
 1307 | Clay_ElementId Clay__dynamicElementIndexBaseHash = (Clay_ElementId) { .id = 128476991, .stringId = CLAY_STRING("Auto ID") };
      |                                                                     ^
/home/huanghaifeng/clay-main/examples/clay-official-website/../../clay.h:1307:69: note: (near initialization for ‘Clay__dynamicElementIndexBaseHash’)
/home/huanghaifeng/clay-main/examples/clay-official-website/../../clay.h:1307:52: error: initializer element is not constant
 1307 | Clay_ElementId Clay__dynamicElementIndexBaseHash = (Clay_ElementId) { .id = 128476991, .stringId = CLAY_STRING("Auto ID") };
      |                                                    ^
/home/huanghaifeng/clay-main/examples/clay-official-website/../../clay.h:2452:82: error: initializer element is not constant
 2452 | Clay_TextElementConfig Clay__DebugView_TextNameConfig = (Clay_TextElementConfig) {.fontSize = 16, .textColor = CLAY__DEBUGVIEW_COLOR_4, .wrapMode = CLAY_TEXT_WRAP_NONE };
      |                                                                                  ^
/home/huanghaifeng/clay-main/examples/clay-official-website/../../clay.h:2452:82: note: (near initialization for ‘Clay__DebugView_TextNameConfig’)
/home/huanghaifeng/clay-main/examples/clay-official-website/../../clay.h:2452:57: error: initializer element is not constant
 2452 | Clay_TextElementConfig Clay__DebugView_TextNameConfig = (Clay_TextElementConfig) {.fontSize = 16, .textColor = CLAY__DEBUGVIEW_COLOR_4, .wrapMode = CLAY_TEXT_WRAP_NONE };
      |                                                         ^
/home/huanghaifeng/clay-main/examples/clay-official-website/main.c:44:68: error: initializer element is not constant
   44 | Clay_TextElementConfig headerTextConfig = (Clay_TextElementConfig) { .fontId = FONT_ID_BODY_24, .fontSize = 24, .textColor = {61, 26, 5, 255} };
      |                                                                    ^
/home/huanghaifeng/clay-main/examples/clay-official-website/main.c:44:68: note: (near initialization for ‘headerTextConfig’)
/home/huanghaifeng/clay-main/examples/clay-official-website/main.c:44:43: error: initializer element is not constant
   44 | Clay_TextElementConfig headerTextConfig = (Clay_TextElementConfig) { .fontId = FONT_ID_BODY_24, .fontSize = 24, .textColor = {61, 26, 5, 255} };
      |                                           ^
/home/huanghaifeng/clay-main/examples/clay-official-website/main.c:45:66: error: initializer element is not constant
   45 | Clay_TextElementConfig blobTextConfig = (Clay_TextElementConfig) { .fontId = FONT_ID_BODY_24, .fontSize = 30, .textColor = COLOR_LIGHT };
      |                                                                  ^
/home/huanghaifeng/clay-main/examples/clay-official-website/main.c:45:66: note: (near initialization for ‘blobTextConfig’)
/home/huanghaifeng/clay-main/examples/clay-official-website/main.c:45:41: error: initializer element is not constant
   45 | Clay_TextElementConfig blobTextConfig = (Clay_TextElementConfig) { .fontId = FONT_ID_BODY_24, .fontSize = 30, .textColor = COLOR_LIGHT };
      |                                         ^
cc1: warning: unrecognized command line option ‘-Wno-initializer-overrides’
make[2]: *** [examples/clay-official-website/CMakeFiles/clay_official_website.dir/build.make:76: examples/clay-official-website/CMakeFiles/clay_official_website.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:313: examples/clay-official-website/CMakeFiles/clay_official_website.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

BTW, when making the `raylib-sidebar-scrolling-container` folder, the `main.c` file has also some errors:
```
/home/huanghaifeng/clay-main/examples/raylib-sidebar-scrolling-container/main.c:14:68: error: initializer element is not constant
   14 | Clay_TextElementConfig headerTextConfig = (Clay_TextElementConfig) { .fontId = FONT_ID_BODY_16, .fontSize = 16, .textColor = {0,0,0,255} };
      |                                                                    ^
/home/huanghaifeng/clay-main/examples/raylib-sidebar-scrolling-container/main.c:14:68: note: (near initialization for ‘headerTextConfig’)
/home/huanghaifeng/clay-main/examples/raylib-sidebar-scrolling-container/main.c:14:43: error: initializer element is not constant
   14 | Clay_TextElementConfig headerTextConfig = (Clay_TextElementConfig) { .fontId = FONT_ID_BODY_16, .fontSize = 16, .textColor = {0,0,0,255} };
      |                                           ^
make[2]: *** [examples/raylib-sidebar-scrolling-container/CMakeFiles/clay_examples_raylib_sidebar_scrolling_container.dir/build.make:76: examples/raylib-sidebar-scrolling-container/CMakeFiles/clay_examples_raylib_sidebar_scrolling_container.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:183: examples/raylib-sidebar-scrolling-container/CMakeFiles/clay_examples_raylib_sidebar_scrolling_container.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by nicbarker** [comment] 2024-09-25 03:38
Thanks, I'll fix those up.

**Comment by nicbarker** [comment] 2024-09-25 09:28
@haifenghuang could you let me know the compiler and version you're using so I can try testing it out? I suspect it's an old version of gcc with outdated rules around const initializers

**Comment by haifenghuang** [comment] 2024-09-25 11:06
> @haifenghuang could you let me know the compiler and version you're using so I can try testing it out? I suspect it's an old version of gcc with outdated rules around const initializers

Below are my `gcc` compiler's version:
```
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by nicbarker** [comment] 2024-09-27 19:43
I think I might have fixed the rest of the issues here - I've been testing on ubuntu 20.4, gcc 9.4 in a docker container.
https://github.com/nicbarker/clay/pull/29
Please let me know if it works for you 🙂

**Comment by nicbarker** [comment] 2024-09-29 08:20
Closing this as actions confirm it's building on gcc 9.4. Please reach out if you believe the issue isn't fixed for you 🙂

**Closed by nicbarker** 2024-09-29 08:20 UTC
Labels: Attempted Fix
